### ISSUE TITLE
error during execution ./loop2.sh - Hyperspacecoin mining

### ISSUE THREAD

**Issue by silvermpx** [ToastPool/yiimp#1]
Hi, i have this error whet running script ./loop2.sh 
How to resolve it ?
Thanks

Error: Call to undefined method HyperspaceRPC::__call() in /var/www/web/yaamp/core/rpc/wallet-rpc.php:689
Stack trace:
#0 /var/www/web/yaamp/core/backend/users.php(61): WalletRPC->__call('validateaddress', Array)
#1 /var/www/web/yaamp/modules/thread/CronjobController.php(87): BackendUsersUpdate()
#2 /var/www/web/framework/web/actions/CInlineAction.php(49): CronjobController->actionRunLoop2()
#3 /var/www/web/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/web/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/web/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/web/yaamp/components/CYiimpConsoleApp.php(125): CController->run('runLoop2')
#7 /var/www/web/runconsole.php(18): CYiimpConsoleApp->runController('cronjob/runLoop...')
#8 {main

**Comment by goodthebest** [comment]
try **sudo  ./loop2.sh**

**Comment by tlightsky** [comment]
@silvermpx 
`BackendUsersUpdate` function basically just try to fix coin symbol when it's null.
in our case, `CoinSymbol = "SPACE"` is a const in stratum server,
i think we can safely comment `BackendUsersUpdate` in `CronjobController.php` for now to solve this problem

@huetsch how do u think

**Comment by silvermpx** [comment]
Yes problem was solved when Space was set in Coin Setup, now seems to be ok
No errors

Отправлено с iPhone
